use-singularity: True
singularity-args:
  " -e --cwd /gonzo -B
  '$PWD/mri_dataset:/gonzo/mri_dataset,$PWD/mri_processed_data:/gonzo/mri_processed_data'"
rerun-incomplete: True
set-threads:
  fastsurfer: 4
  freesurfer: 4
